project:
  type: website
  output-dir: docs

website:
  title: "Scientific Computing and Model Exploration"
  site-url: "https://migp11.github.io/mini-course-scicomp/"

  navbar:
    search: true

  page-footer:
    center: |
      Scientific Computing Mini-Course · Miguel Ponce de Leon · 2026

  sidebar:
    style: docked
    collapse-level: 2
    contents:
      - index.qmd
      - lectures.qmd
      - practical.qmd
      - references.qmd

format:
  html:
    theme: flatly
    toc: false